# Changes here will be overwritten by Copier
_commit: 15d4481
_src_path: https://github.com/oarepo/nrp-app-copier
languages: ''
repository_description: 'Czech bioimaging repository

    '
repository_human_name: C-bird repository
