# Changes here will be overwritten by Copier
_commit: 21e842e
_src_path: https://github.com/oarepo/nrp-model-copier
base_model: rdm_complete
model_description: 'High-level datasets

    '
model_human_name: Datasets
